TASKS = [
    {
        "id": "easy_triage",
        "task_id": "easy_triage",
        "name": "easy_triage",
        "difficulty": "easy",
        "description": "5 clear-signal emails — unambiguous priority, category, routing",
        "max_steps": 5,
        "reset_params": {"task_name": "easy_triage"},
        "action_schema": {
            "priority": "urgent | high | normal | low",
            "category": "billing | technical_support | feature_request | bug_report | account_management | sales_inquiry | general_inquiry | spam",
            "routing_target": "tier1_support | tier2_support | billing_team | sales_team | engineering | account_management | spam_filter | escalation",
            "sentiment": "positive | neutral | negative | very_negative",
            "requires_followup": "boolean",
            "summary": "string",
            "suggested_response_tone": "formal | friendly | empathetic | concise",
            "tags": "list of strings (0-5)",
            "task_id": "easy_triage",
        },
        "grader": "graders:grade_easy_triage",
        "graders": ["graders:grade_easy_triage"],
        "reward_range": [0.0, 1.0],
    },
    {
        "id": "medium_triage",
        "task_id": "medium_triage",
        "name": "medium_triage",
        "difficulty": "medium",
        "description": "5 emails with mixed signals, thread context, multi-part issues",
        "max_steps": 5,
        "reset_params": {"task_name": "medium_triage"},
        "action_schema": {
            "priority": "urgent | high | normal | low",
            "category": "billing | technical_support | feature_request | bug_report | account_management | sales_inquiry | general_inquiry | spam",
            "routing_target": "tier1_support | tier2_support | billing_team | sales_team | engineering | account_management | spam_filter | escalation",
            "sentiment": "positive | neutral | negative | very_negative",
            "requires_followup": "boolean",
            "summary": "string",
            "suggested_response_tone": "formal | friendly | empathetic | concise",
            "tags": "list of strings (0-5)",
            "task_id": "medium_triage",
        },
        "grader": "graders:grade_medium_triage",
        "graders": ["graders:grade_medium_triage"],
        "reward_range": [0.0, 1.0],
    },
    {
        "id": "hard_triage",
        "task_id": "hard_triage",
        "name": "hard_triage",
        "difficulty": "hard",
        "description": "5 ambiguous emails with churn risk, legal implications, competing signals",
        "max_steps": 5,
        "reset_params": {"task_name": "hard_triage"},
        "action_schema": {
            "priority": "urgent | high | normal | low",
            "category": "billing | technical_support | feature_request | bug_report | account_management | sales_inquiry | general_inquiry | spam",
            "routing_target": "tier1_support | tier2_support | billing_team | sales_team | engineering | account_management | spam_filter | escalation",
            "sentiment": "positive | neutral | negative | very_negative",
            "requires_followup": "boolean",
            "summary": "string",
            "suggested_response_tone": "formal | friendly | empathetic | concise",
            "tags": "list of strings (0-5)",
            "task_id": "hard_triage",
        },
        "grader": "graders:grade_hard_triage",
        "graders": ["graders:grade_hard_triage"],
        "reward_range": [0.0, 1.0],
    },
]

TASK_ID_TO_INDEX = {
    "easy_triage": 0,
    "medium_triage": 1,
    "hard_triage": 2,
}

TASK_GRADER_PAIRS = [
    ("easy_triage", "graders:grade_easy_triage"),
    ("medium_triage", "graders:grade_medium_triage"),
    ("hard_triage", "graders:grade_hard_triage"),
]

__all__ = ["TASKS", "TASK_ID_TO_INDEX", "TASK_GRADER_PAIRS"]